name: Unity Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Run Unity tests
        run: make tests
